version: '3.8'
#describe what the docker does
services:
  backend:
    build:
      context: ./backend
    expose:
      - "8000"
    environment:
      - YOUR_ENV_VARIABLES_HERE
    networks:
      - app-network
    init: true

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount Let's Encrypt SSL certificates from the host
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - backend

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/letsencrypt:/etc/letsencrypt:rw  # SSL certificates shared with Nginx
    environment:
      - NGINX_PROXY_CONTAINER=nginx
      - DEFAULT_EMAIL=fionaxu.sh@outlook.com
    depends_on:
      - nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

